application: webicarus1
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
  
- url: /(about|privacy|contacts|gallery|sitemap)
  script: main.py

- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /images
  static_dir: images

inbound_services:
- mail
