application: webicarus1
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /images
  static_dir: images

- url: /addNews
  script: main.py
  login: admin 

- url: /(.*)
  script: main.py

inbound_services:
- mail
